### ISSUE TITLE
Comparison with `Union{T, E}`

### ISSUE THREAD

**Issue by ylxdzsw** [KristofferC/Expect.jl#2]
First of all, neat package!

I'm curious about the difference between this package and just `Union{T, E}`. In the latter case, `isassigned` can be replaced with `isa(_, Exception)`, and `a[]` is not even needed. Specifying return type is not required too, though of course should be encouraged in this case. In the case where `T` can also be an exception, `Some` from `Base` can be used.

In my opinion `Union{T, E}` gives the advantage of better optimization and flexibility. For example if you are calling `mapreduce(f, g, ...)` where `f` might return an exception. Assuming `f` returns `Union{T, E}` means you can replace `f` with `f2` which always success without changing the definition of `g`, in which case `isa(_, Exception)` inside `g` is also optimized out at compile time.

**Comment by KristofferC** [comment]
I have thought about the same thing and here are my comments

>  In the latter case, isassigned can be replaced with `isa(_, Exception)`

You would need something like

```jl
a = foo()
if a isa Exception
    throw(a)
else
    ...
end
```

If you just keep using `a` without checking anything you will get a weird MethodError instead of a proper throw.


> and `a[]` is not even needed. 

That is a disadvantage imo. In Pkg.jl we have the following bug report https://github.com/JuliaLang/Pkg.jl/issues/822. This is because we have a function that returns `Union{T, Nothing}` and we forget to check for `Nothing` in one place and handle it correctly. By forcing `[]` one needs to think about handling the error, or if one doesn't then a proper exception is thrown.

> In my opinion Union{T, E} gives the advantage of better optimization 

I benchmarked things and they are pretty fast. Do you have some benchmark showing this.

> which always success without changing the definition of g

The point here is kinda to force handling of the error which is the opposite of existing code just keep working.

**Comment by ylxdzsw** [comment]
## about the syntax

```
a = foo()
if a isa Exception
    throw(a)
else
    ...
end
````

is not longer than

```
a = foo()
if isassigned(a)
    ...a[]...
else
    handle error
end
```

right? And one can always define thier functions or macros to make it simpler. For example

```
a = @some foo() # it returns or throw if `foo()` returns an exception
```

## about `a[]`

Yes, that's somewhat an advantage to force write `a[]`. However, I think not force it is also not too bad. For example, for throwaway scripts that run in REPL, I'd like to not deal with the hassle of error handling and just make it run (just like you won't `try catch` when reading a file in terminal). When errors happen, the `MethodError` might be strange, but it still contains enough information (the type of Exception) to understand the situation. For code that might be reused, there are also many ways to help track down the problem. For example, I personally always use `@code_warntype` to check type stability, and it clearly shows when possible errors are not handled.

## About performance and flexibility

I talk these together since they are a trade-off in this case. In the following example, I have a generic function `g` that always check for exception regardless of whether the parameter `f` errors or not. I think this is the encouraged style right?

```
# type parameter T do not handle the case when x is integer and result is float
# so I have to use abstract return type AbstractFloat to keep generic
function f_expect_error(x)::Expected{AbstractFloat, DivideError}
    if x == 0
        return DivideError()
    else
        1 / x
    end
end

# I have to make it return Expected since upstream code expects an Expected
function f_expect_noerror(x)::Expected{AbstractFloat, DivideError}
    2 * x
end

function g_expect(f, x::Vector)
    mapreduce(+, x) do x
        y = f(x)
        isassigned(y) ? y[] : 0
    end
end

function f_union_error(x)::Union{AbstractFloat, DivideError}
    if x == 0
        return DivideError()
    else
        1 / x
    end
end

function f_union_noerror(x)::Union{AbstractFloat, DivideError}
    2 * x
end

function g_union(f, x::Vector)
    mapreduce(+, x) do x
        y = f(x)
        y isa Exception ? 0 : y
    end
end
```

And this is the benchmark.

```
julia> @btime g_expect(f_expect_error, rand(5000))
  3.754 ms (15001 allocations: 273.50 KiB)
38802.82985418331

julia> @btime g_expect(f_expect_noerror, rand(5000))
  3.794 ms (15001 allocations: 273.50 KiB)
4981.134637018143

julia> @btime g_union(f_union_error, rand(5000))
  21.424 μs (2 allocations: 39.14 KiB)
49259.158625474796

julia> @btime g_union(f_union_noerror, rand(5000))
  4.616 μs (2 allocations: 39.14 KiB)
5048.402252641862
```

The `Union` performs better especially when `f` actually never error since the compiler can infer it and optimize `g` accordingly.

## The point here is kinda to force handling of the error which is the opposite of existing code just keep working.

Just like the above example, my argument is that `g` can always deal with exceptions but still happy to accept `f` that never error (returns T rather than an Expect) without changing its own definition.

**Comment by KristofferC** [comment]
How about if you have something like

```
v = foo() # returns an exception or a value
print(io, v)
```

Pretty much anything (including exceptions) can be printed to `io`. How would you know that you have an error in your code.

> And one can always define thier functions or macros to make it simpler

And then you forget to use it...

**Comment by ylxdzsw** [comment]
Wouldn't the situation the same with `Expected`? You can also forget to write `a[]` and just do `print(io, a)` and see the strange `Expected` in the output, like `Exception` in this case.

**Comment by KristofferC** [comment]
That code would **always** be wrong, not just in the unexpected case. Of course, it is impossible to protect against all bugs but the idea is to find the bug assuming the code works in the expected case.
